#!/bin/bash

#IP_ADDRESS=$(ip route get 1 | awk '{print $NF;exit}')
IP_ADDRESS=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | head -n 1)

if [[ "${IP_ADDRESS}" != "" ]]; then
  echo "${IP_ADDRESS}"
  echo "${IP_ADDRESS}"
  echo ""
fi
